Updated ``Entities.SyncPlan`` code.
Updated ``entities.SyncPlan`` with ``orm.EntityReadMixin``,
``orm.EntityDeleteMixin`` and ``orm.EntityCreateMixin`` so we can start
writing automated tests for ``Sync Plans`` via API.

The implementation does not follow the standard format for most other
available ``entities`` and it closely mimics what we currently do with
``entities.OperatingSystemParameter``, where an existing organization ID
is required in order to perform CRUD actions.

```python
In [1]: from robottelo import entities

In [2]: from fauxfactory import gen_datetime

In [3]: entities.SyncPlan(organization_id=1).create_json()

Out[3]:
{u'created_at': u'2015-02-28T17:39:19Z',
 u'description': None,
 u'enabled': False,
 u'id': 30,
 u'interval': u'weekly',
 u'name': u'\u1eec\u3119\u72f6\u61f3\u19c6\u76f1\ube77\u6905\u995c\u182b\u6632\ud439\u7f35\u5f1c\uc23a\u5dcc\ufc17\u5a51\u8cac\u6e07\u6940',
 u'next_sync': u'2709-07-09T19:45:18Z',
 u'organization_id': 1,
 u'permissions': {u'destroy_sync_plans': True,
  u'edit_sync_plans': True,
  u'view_sync_plans': True},
 u'products': [],
 u'sync_date': u'2709-07-09T19:45:18Z',
 u'updated_at': u'2015-02-28T17:39:19Z'}

In [4]: entities.SyncPlan(organization_id=1, id=30).read_json()

Out[4]:
{u'created_at': u'2015-02-28T17:39:19Z',
 u'description': None,
 u'enabled': False,
 u'id': 30,
 u'interval': u'weekly',
 u'name': u'\u1eec\u3119\u72f6\u61f3\u19c6\u76f1\ube77\u6905\u995c\u182b\u6632\ud439\u7f35\u5f1c\uc23a\u5dcc\ufc17\u5a51\u8cac\u6e07\u6940',
 u'next_sync': u'2709-07-09T19:45:18Z',
 u'organization_id': 1,
 u'permissions': {u'destroy_sync_plans': True,
  u'edit_sync_plans': True,
  u'view_sync_plans': True},
 u'products': [],
 u'sync_date': u'2709-07-09T19:45:18Z',
 u'updated_at': u'2015-02-28T17:39:19Z'}

In [5]: entities.SyncPlan(organization_id=1, id=30).delete()

Out[5]:
{u'created_at': u'2015-02-28T17:39:19Z',
 u'description': None,
 u'enabled': False,
 u'id': 30,
 u'interval': u'weekly',
 u'name': u'\u1eec\u3119\u72f6\u61f3\u19c6\u76f1\ube77\u6905\u995c\u182b\u6632\ud439\u7f35\u5f1c\uc23a\u5dcc\ufc17\u5a51\u8cac\u6e07\u6940',
 u'next_sync': u'2709-07-09T19:45:18Z',
 u'organization_id': 1,
 u'permissions': {u'destroy_sync_plans': True,
  u'edit_sync_plans': True,
  u'view_sync_plans': True},
 u'products': [],
 u'sync_date': u'2709-07-09T19:45:18Z',
 u'updated_at': u'2015-02-28T17:39:19Z'}

In [6]: entities.SyncPlan(organization_id=1, id=30).read_json()

HTTPError: 404 Client Error: Not Found

In [7]: random_datetime = gen_datetime()

In [8]: random_datetime
Out[8]: datetime.datetime(2206, 5, 26, 6, 1, 19, 659751)

In [9]: entities.SyncPlan(organization_id=1, interval='hourly', enabled=True, sync_date=random_datetime).create_json()

Out[9]:
{u'created_at': u'2015-02-28T17:41:41Z',
 u'description': None,
 u'enabled': True,
 u'id': 31,
 u'interval': u'hourly',
 u'name': u'\u9d0e\u6972\u7b63\ua652\u6678\u9a7e\u5a6c\u3c8f\u01cf\uc138\ud041\u5245\u5b50\ub3d4\u6399\ucf31\u829b\u4181\u3084\u5323\u63da\ud732',
 u'next_sync': u'2206-05-26T06:01:19Z',
 u'organization_id': 1,
 u'permissions': {u'destroy_sync_plans': True,
  u'edit_sync_plans': True,
  u'view_sync_plans': True},
 u'products': [],
 u'sync_date': u'2206-05-26T06:01:19Z',
 u'updated_at': u'2015-02-28T17:41:41Z'}
```