Fixes and updates CLI tests for OS.
Basically our existing CLI tests for Operating System were either
completely outdated/broken or badly implemented. I have removed a few
redundant tests and improved the existing data-driven CRUD tests.

All tests are GREEN except for the test for an existing Bugzilla issue,
which is ON_QA but the fix has not yet landed on latest compose build.

```bash
nosetests -c robottelo.properties tests/cli/test_os.py
INFO ssh:61: Paramiko instance prepared (and would be reused): 0x104b76e90
@test: Update an Operating System's major version. ... ERROR
@test: Displays info for operating system ... ok
@test: Displays list for operating system ... ok
@test: Create Operating System using invalid names ... ok
@test: Create Operating System using invalid names ... ok
@test: Create Operating System using invalid names ... ok
@test: Create Operating System using invalid names ... ok
@test: Create Operating System using invalid names ... ok
@test: Create Operating System using invalid names ... ok
@test: Create Operating System using invalid names ... ok
@test: Not delete Operating System for invalid data ... ok
@test: Not delete Operating System for invalid data ... ok
@test: Not delete Operating System for invalid data ... ok
@test: Not delete Operating System for invalid data ... ok
@test: Not delete Operating System for invalid data ... ok
@test: Negative update of system name ... ok
@test: Negative update of system name ... ok
@test: Negative update of system name ... ok
@test: Negative update of system name ... ok
@test: Negative update of system name ... ok
@test: Negative update of system name ... ok
@test: Negative update of system name ... ok
@test: Create Operating System for all variations of name ... ok
@test: Create Operating System for all variations of name ... ok
@test: Create Operating System for all variations of name ... ok
@test: Create Operating System for all variations of name ... ok
@test: Create Operating System for all variations of name ... ok
@test: Create Operating System for all variations of name ... ok
@test: Successfully deletes Operating System ... ok
@test: Successfully deletes Operating System ... ok
@test: Successfully deletes Operating System ... ok
@test: Successfully deletes Operating System ... ok
@test: Successfully deletes Operating System ... ok
@test: Positive update of system name ... ok
@test: Positive update of system name ... ok
@test: Positive update of system name ... ok
@test: Positive update of system name ... ok
@test: Positive update of system name ... ok
@test: Positive update of system name ... ok
@test: Search for newly created OS by name ... SKIP: Test skipped due to Redmine issue #4547

======================================================================
ERROR: @test: Update an Operating System's major version.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/omaciel/hacking/robottelo/tests/cli/test_os.py", line 129, in test_bugzilla_1051557
    result = OperatingSys.info({'id': result.stdout['id']})
TypeError: list indices must be integers, not str

----------------------------------------------------------------------
XML: foreman-results.xml
----------------------------------------------------------------------
Ran 40 tests in 397.463s

FAILED (SKIP=1, errors=1)
```