Add PhamtomJS as a choice for WebDriver.
PhamtomJS could be very useful for running UI tests in headless mode.
Also, there's no need to set the logging level anywhere outside the
initial setup.

For what is worth, I only ran one test using PhamtomJS and it failed
because it couldn't find the New User button:

```bash
$ nosetests -c robottelo.properties tests/ui/test_user.py:User.test_create_user
Create a new User ... ERROR

======================================================================
ERROR: Create a new User
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/omaciel/hacking/robottelo/tests/ui/test_user.py", line 42, in test_create_user
    self.create_user(name, password, email, search_key)
  File "/Users/omaciel/hacking/robottelo/tests/ui/test_user.py", line 29, in create_user
    self.user.create(name, email, password, password)
  File "/Users/omaciel/hacking/robottelo/robottelo/ui/user.py", line 31, in create
    self.wait_until_element(locators["users.new"]).click()
AttributeError: 'NoneType' object has no attribute 'click'

----------------------------------------------------------------------
XML: foreman-results.xml
----------------------------------------------------------------------
Ran 1 test in 42.526s

FAILED (errors=1)
```