[6.16.z] Fix cli yum repo authentication test (#16769)
Fix cli yum repo authentication test (#16640)

There were multiple levels to this error:

* fix parametrization error
  AttributeError: 'generator' object has no attribute 'copy'
* fix assertion
* filter invalid parametrizations by adding 'yum_compatible' flag
  - 'latin-1' codec can't encode characters
  - Validation failed: Upstream password requires upstream username be set.
  - Validation failed: Upstream username is too long (maximum is 255 characters)

What was sadly not done:
* make parametrization ids readable for meanigful debugging

(cherry picked from commit 1b4ad6332ce4ec87a2f637467bd61b213295a16c)

Co-authored-by: dosas <dosas@users.noreply.github.com>