Skip API tests that fail due to BZ 1187366
From the bug report:

    It is impossible to delete an organization or environment. Doing so results
    an HTTP 500 error and the following error message:

        "undefined method `disable_auto_reindex!' for #<Katello::KTEnvironment:0x007feabd86dc10>"

    To be even more exact, issuing an HTTP DELETE request to the following URLs
    triggers the above error:

    * my-satellite6.example.com/katello/api/v2/organizations/:organization_id
    * my-satellite6.example.com/katello/api/v2/environments/:environment_id

The test suite passes a sanity check:

    $ nosetests tests/foreman/api/test_multiple_paths.py -m Organization
    S..S......S
    ----------------------------------------------------------------------
    Ran 11 tests in 11.772s

    OK (SKIP=3)