Switch to unittest2
All occurrences of unittest should have been caught, except for the references
in the documentation. (And the documentation needs quite a few updates, at this
point.)

    $ git grep -i 'unittest[\. ]'
    docs/index.rst:    $ python -m unittest discover -s tests/robottelo -t .
    docs/index.rst:    $ python -m unittest discover -s tests/foreman -t .
    docs/index.rst:    $ python -m unittest discover \
    docs/index.rst:    $ python -m unittest tests.robottelo.test_decorators
    docs/index.rst:    $ python -m unittest tests.robottelo.test_decorators.DataDecoratorTestCase
    docs/index.rst:    $ python -m unittest tests.robottelo.test_decorators.DataDecoratorTestCase.test_data_decorator_smoke
    docs/index.rst:    $ python -m unittest discover -s tests/ -t . -v
    docs/index.rst:    $ python -m unittest \
    docs/index.rst:    $ python -m unittest discover -s tests/foreman/api/
    docs/index.rst:    $ python -m unittest discover -s tests/foreman/cli/
    docs/index.rst:    $ python -m unittest discover -s tests/foreman/ui/
    docs/index.rst:.. _unittest: http://docs.python.org/2/library/unittest.html

Pylint results:

    $ pylint -j 4 --reports n $(git diff master --name-only) | grep -i unittest
    No config file found, using default configuration
    W: 34, 0: FIXME: Use unittest2's subTest context manager instead of this and @ddt.data. (fixme)

Sample CLI test results:

    $ make test-foreman-cli
    python -m cProfile -o test-foreman-cli.pstats $(which nosetests) --logging-filter=nailgun,robottelo --with-xunit --xunit-file=foreman-results.xml tests/foreman/cli
    .....ESSSSSSSSS...........SSSSSSS.SSSSSS.
    ======================================================================
    ERROR: @Test: Test that subscription can be added to activation key
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ichimonji10/code/robottelo/tests/foreman/cli/test_activationkey.py", line 1416, in test_add_subscription
        manifest = manifests.clone()
      File "robottelo/manifests.py", line 167, in clone
        with zipfile.ZipFile(new_path) as oldzip:
      File "/usr/lib64/python2.7/zipfile.py", line 770, in __init__
        self._RealGetContents()
      File "/usr/lib64/python2.7/zipfile.py", line 811, in _RealGetContents
        raise BadZipfile, "File is not a zip file"
    BadZipfile: File is not a zip file

    ----------------------------------------------------------------------
    Ran 41 tests in 284.720s

    FAILED (SKIP=22, errors=1)

Sample UI test results:

    $ make test-foreman-ui
    python -m cProfile -o test-foreman-ui.pstats $(which nosetests) --logging-filter=nailgun,robottelo --with-xunit --xunit-file=foreman-results.xml tests/foreman/ui
    .E.^C
    ======================================================================
    ERROR: @Test: Test that RH product can be associated to Activation Keys
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ichimonji10/code/robottelo/tests/foreman/ui/test_activationkey.py", line 1191, in test_associate_product_1
        with open(manifests.clone(), 'rb') as manifest:
      File "robottelo/manifests.py", line 167, in clone
        with zipfile.ZipFile(new_path) as oldzip:
      File "/usr/lib64/python2.7/zipfile.py", line 770, in __init__
        self._RealGetContents()
      File "/usr/lib64/python2.7/zipfile.py", line 811, in _RealGetContents
        raise BadZipfile, "File is not a zip file"
    BadZipfile: File is not a zip file

    ----------------------------------------------------------------------
    Ran 3 tests in 179.495s

    FAILED (errors=1)

I believe the failed tests are due to a partially configured configuration file,
not the changes herein.