Fix AttributeError: module 'nailgun.entities' has no attribute 'ConfigTemplate'
(ConfigTemplate was removed in nailgun but no action done in robottelo)