[6.16.z] Make the sphinx check more resilient (#17740)
Make the sphinx check more resilient (#17701)

Just saw an issue in the robottelo CI where this popped up.

  File "/home/runner/work/robottelo/robottelo/robottelo/config/__init__.py", line 25, in get_settings
    if builtins.__sphinx_build__:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'builtins' has no attribute '__sphinx_build__'

If we simply make this a getattr call, then we don't have to worry about that attribute being present.

(cherry picked from commit ed9a7a01f0bcd78ebad40855d170a4a4506c5407)

Co-authored-by: Jake Callahan <jacob.callahan05@gmail.com>