Make test assertions more verbose
Several API tests in module  `tests.foreman.api.test_contentview` are currently
failing when executed by Jenkins:

* `test_positive_publish_2`
* `test_positive_promote_1`
* `test_positive_promote_2`

Unfortunately, the error messages produced by those tests are not especially
helpful. For example:

> AssertionError: u'error' != 'success'

Also, the failures cannot be reproduced manually, and they therefore cannot be
diagnosed. Make the test assertions more verbose so that more information is
emitted by Jenkins.