Fix hot backup/restore tests
1. Increased timeout for `satellite-backup` command as it takes around 3 mins locally on fresh satellite, so no surprise tests are failing on jenkins with
```
SSHCommandTimeoutError: ssh command: satellite-backup -y /tmp/RzYtzVsIcA --logical-db-backup   did not respond in the predefined time (timeout=300)
```
error
2. Replaced tearDownClass with tearDown, this way we'll ensure services are started after each test and will fix failures like
```
ConnectionError: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: /api/v2/users (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f685c474f90>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
3. Incremental online backup is not working for 6.3 per http://bugzilla.redhat.com/show_bug.cgi?id=1527957, skipped affected tests