API test overhaul omnibus
Update to NailGun 0.17.0. Use the updates therein and updates provided by
previous releases to update nearly every single API test module. Review existing
tests and make them use higher-level methods when possible. For example:

* Use the `create` method instead of the `create_json` method.
* Use the `update` method instead of the `client.put` function.

Do not update module `tests.foreman.api.test_multiple_paths`. It is in need of
an update on several levels, and an update to it will come in a separarate pull
request. Test results against a downstream RHEL 6.6 system:

    $ make test-foreman-api-threaded
    python -m cProfile -o test-foreman-api-threaded.pstats $(which nosetests) --logging-filter=nailgun,robottelo --with-xunit --xunit-file=foreman-results.xml tests/foreman/api\
        --processes=-1 --process-timeout=300
    ....SSS.....................S.........EEE..E..EE................E.......SSSSSSSSSSSSSSSSSSSSSSSS........SSSSSSSSSSSSSSSSSSSSSSS.SS.............SSSS..SSSSSSSSS...........S.SSSSSSSESSSSSS................................................S.........SSSSSSSSSSSSS...S..S...S..SSS.SSSSSSS.................SSSSSSSS......S..S.......S.........................................................................SS.....................................................................................S...............................................................SSSSS.S.SSSSSSSS.S..SSS.S..SSSSSSSSSSSSSSSSSSSSSSSSSSSSS..................S....S........................................................S...............E..........................................SSSSSSSS..EESSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.S.S.SS.SSSSSSSSSSSSSSSSSSSSSS.............................................
    ======================================================================
    ERROR: @Test: Give a content view yum packages and publish it repeatedly.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_contentview.py", line 377, in test_positive_publish_2
        content_view.publish()
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 1138, in publish
        return _handle_response(response, self._server_config, synchronous)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 105, in _handle_response
        return ForemanTask(server_config, id=response.json()['id']).poll()
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 1416, in poll
        timeout
    File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 105, in _poll_task
        task_info['humanized']['errors']
    TaskFailedError: Task dc73a51f-d071-4996-84be-3c5c0e6b5110 completed with result error. Error message(s): [u'ERF12-4115 [ProxyAPI::ProxyException]: Unable to get classes from Puppet for KT_d79c4b77_bfda_4ef6_aa43_71051c6b2d38_Library_9b32b146_c5c2_4569_9ed2_bb842ee79b51_1005 ([RestClient::NotAcceptable]: 406 Not Acceptable) for proxy https://sat.example.com:9090/puppet']

    ======================================================================
    ERROR: @Test: Create empty composite view and assign random number of
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_contentview.py", line 734, in test_promote_composite_cv_once_2
        self.add_content_views_to_composite(composite_cv, random.randint(3, 5))
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_contentview.py", line 338, in add_content_views_to_composite
        content_view.publish()
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 1138, in publish
        return _handle_response(response, self._server_config, synchronous)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 105, in _handle_response
        return ForemanTask(server_config, id=response.json()['id']).poll()
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 1416, in poll
        timeout
    File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 105, in _poll_task
        task_info['humanized']['errors']
    TaskFailedError: Task e6768ea2-35fb-4a77-92b9-b28f232022fb completed with result error. Error message(s): [u'ERF12-2749 [ProxyAPI::ProxyException]: Unable to get environments from Puppet ([RestClient::NotAcceptable]: 406 Not Acceptable) for proxy https://sat.example.com:9090/puppet']

    ======================================================================
    ERROR: @Test: Create empty composite view and assign one normal content
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_contentview.py", line 713, in test_promote_composite_cv_once_1
        entities.LifecycleEnvironment(organization=self.org).create().id
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 881, in promote
        return _handle_response(response, self._server_config, synchronous)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 105, in _handle_response
        return ForemanTask(server_config, id=response.json()['id']).poll()
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 1416, in poll
        timeout
    File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 105, in _poll_task
        task_info['humanized']['errors']
    TaskFailedError: Task c6905800-dc47-4fbb-bc6b-3c7f21d4083a completed with result error. Error message(s): [u'ERF12-4115 [ProxyAPI::ProxyException]: Unable to get classes from Puppet for KT_70b2a010_e99a_4bba_a329_aa0f0dff1435_7d31fa86_cfa2_47e4_bd08_f9c5a22f23d5_48f29524_1d64_4832_8559_0503976bd619_1012 ([RestClient::NotAcceptable]: 406 Not Acceptable) for proxy https://sat.example.com:9090/puppet']

    ======================================================================
    ERROR: @Test: Give a content view a puppet module, publish it once and
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_contentview.py", line 628, in test_promote_cv_with_puppet_multiple
        content_view.version[0].promote(lce.id)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 881, in promote
        return _handle_response(response, self._server_config, synchronous)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 105, in _handle_response
        return ForemanTask(server_config, id=response.json()['id']).poll()
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 1416, in poll
        timeout
    File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 105, in _poll_task
        task_info['humanized']['errors']
    TaskFailedError: Task 0ab7f1ea-05e7-405e-92c8-90a098f5bfc0 completed with result error. Error message(s): [u'ERF12-2749 [ProxyAPI::ProxyException]: Unable to get environments from Puppet ([RestClient::NotAcceptable]: 406 Not Acceptable) for proxy https://sat.example.com:9090/puppet']

    ======================================================================
    ERROR: @Test: Create empty composite view and assign random number of
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_contentview.py", line 795, in test_promote_composite_cv_multiple_2
        composite_cv.version[0].promote(lce.id)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 881, in promote
        return _handle_response(response, self._server_config, synchronous)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 105, in _handle_response
        return ForemanTask(server_config, id=response.json()['id']).poll()
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 1416, in poll
        timeout
    File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 95, in _poll_task
        raise TaskTimedOutError('Timed out polling task {0}'.format(task_id))
    TaskTimedOutError: Timed out polling task 9d98f25c-92d2-41ba-b68a-a31784aa8c19

    ======================================================================
    ERROR: @Test: Publish a content view that has puppet module once.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/nose/plugins/multiprocess.py", line 812, in run
        test(orig)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/nose/case.py", line 45, in __call__
        return self.run(*arg, **kwarg)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/nose/case.py", line 133, in run
        self.runTest(result)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
        test(result)
    File "/usr/lib64/python2.7/unittest/case.py", line 395, in __call__
        return self.run(*args, **kwds)
    File "/usr/lib64/python2.7/unittest/case.py", line 331, in run
        testMethod()
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_contentview.py", line 470, in test_publish_cv_with_puppet_once
        content_view = entities.ContentView(organization=self.org).create()
    File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 837, in create
        return self.read(attrs=self.create_json(create_missing))
    File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 807, in create_json
        response = self.create_raw(create_missing)
    File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 792, in create_raw
        **self._server_config.get_client_kwargs()
    File "/home/ichimonji10/code/nailgun/nailgun/client.py", line 163, in post
        response = requests.post(url, data, json, **kwargs)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/api.py", line 109, in post
        return request('post', url, data=data, json=json, **kwargs)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/api.py", line 50, in request
        response = session.request(method=method, url=url, **kwargs)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
        resp = self.send(prep, **send_kwargs)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
        r = adapter.send(request, **kwargs)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
        timeout=timeout
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
        body=body, headers=headers)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
        self._validate_conn(conn)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
        conn.connect()
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 204, in connect
        conn = self._new_conn()
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/packages/urllib3/util/connection.py", line 78, in create_connection
        sock.connect(sa)
    File "/usr/lib64/python2.7/socket.py", line 228, in meth
        return getattr(self._sock,name)(*args)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/nose/plugins/multiprocess.py", line 276, in signalhandler
        raise TimedOutException()
    TimedOutException: 'test_publish_cv_with_puppet_once (tests.foreman.api.test_contentview.CVPublishPromoteTestCase)'

    ======================================================================
    ERROR: test suite for <class 'tests.foreman.api.test_contentview.CVRedHatContent'>
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/nose/plugins/multiprocess.py", line 788, in run
        self.setUp()
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
        self.setupContext(ancestor)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/nose/plugins/multiprocess.py", line 770, in setupContext
        super(NoSharedFixtureContextSuite, self).setupContext(context)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
        try_run(context, names)
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
        return func()
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_contentview.py", line 870, in setUpClass
        releasever='7Server',
    File "robottelo/api/utils.py", line 118, in enable_rhrepo_and_fetchid
        reposet_id = entities.Product(id=prd_id).fetch_reposet_id(name=reposet)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 2621, in fetch_reposet_id
        "The length of the results is:", len(results))
    APIResponseError: ('The length of the results is:', 0)

    ======================================================================
    ERROR: @Test: Create and sync a Docker-type repository
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "robottelo/common/decorators.py", line 375, in wrapper_func
        return func(*args, **kwargs)
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_docker.py", line 473, in test_add_synced_docker_repo_to_content_view
        repo.sync()
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 2868, in sync
        return _handle_response(response, self._server_config, synchronous)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 105, in _handle_response
        return ForemanTask(server_config, id=response.json()['id']).poll()
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 1416, in poll
        timeout
    File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 87, in _poll_task
        response.raise_for_status()
    File "/home/ichimonji10/.virtualenvs/robottelo/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    HTTPError: 500 Server Error: Internal Server Error

    ======================================================================
    ERROR: @Test: Sync RedHat Repository.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_repository.py", line 257, in test_redhat_sync_1
        '7Server',
    File "robottelo/api/utils.py", line 118, in enable_rhrepo_and_fetchid
        reposet_id = entities.Product(id=prd_id).fetch_reposet_id(name=reposet)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 2621, in fetch_reposet_id
        "The length of the results is:", len(results))
    APIResponseError: ('The length of the results is:', 0)

    ======================================================================
    ERROR: @Test: Upload a manifest.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_subscription.py", line 26, in test_positive_create_1
        org.upload_manifest(path=cloned_manifest_path)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 2250, in upload_manifest
        return _handle_response(response, self._server_config, synchronous)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 105, in _handle_response
        return ForemanTask(server_config, id=response.json()['id']).poll()
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 1416, in poll
        timeout
    File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 105, in _poll_task
        task_info['humanized']['errors']
    TaskFailedError: Task 2dd5a134-61f8-466e-8784-3f6f1c1a47e2 completed with result warning. Error message(s): [u'Runtime Error ERROR: deadlock detected\n  Detail: Process 2388 waits for ShareLock on transaction 466557; blocked by process 16991.\nProcess 16991 waits for ExclusiveLock on tuple (5,1) of relation 16581 of database 16387; blocked by process 2388.\n  Hint: See server log for query details. at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse:2,094']

    ======================================================================
    ERROR: @Test: Upload the same manifest to two organizations.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_subscription.py", line 53, in test_negative_create_1
        orgs[0].upload_manifest(manifest_path)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 2250, in upload_manifest
        return _handle_response(response, self._server_config, synchronous)
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 105, in _handle_response
        return ForemanTask(server_config, id=response.json()['id']).poll()
    File "/home/ichimonji10/code/nailgun/nailgun/entities.py", line 1416, in poll
        timeout
    File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 105, in _poll_task
        task_info['humanized']['errors']
    TaskFailedError: Task 978ed730-607f-4fe9-a29f-30298729384a completed with result warning. Error message(s): [u'Runtime Error Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1 at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched:81']

    ======================================================================
    FAIL: @Test: Delete a content-view version associated to 'Library'
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_contentviewversion.py", line 69, in test_delete_version
        self.assertEqual(content_view.version[0].id, 1)
    AssertionError: 969 != 1

    ----------------------------------------------------------------------
    Ran 858 tests in 1987.516s

    FAILED (SKIP=236, errors=11)

File several bugs and consequently fix several Jenkins failures. See:

* https://bugzilla.redhat.com/show_bug.cgi?id=1230865
* https://bugzilla.redhat.com/show_bug.cgi?id=1230873
* https://bugzilla.redhat.com/show_bug.cgi?id=1230902