Fixing ``content-host`` CLI failures.
Jenkins was showing that some of the existing CLI tests for
``content-host`` were failing due to the fact that the argument
``environment-id`` has been changed to ``lifecycle-environment-id``, so
tests were failing:

```bash
Error: Unrecognised option '--environment-id'
```

Using my ``BDFL`` powers and merging directly to ``master``.